@startuml purchase_schema

!include lib/schema-style.iuml

Table(shopping_cart_stock_item_purchase_options) {
    primary_key(id) : INT
    <color:green>license_fee_id: INT</color>
}

Table(shopping_cart_purchase_stock_items) {
    primary_key(id) : INT
    <color:green>license_fee: DECIMAL</color>
}

Table(stock_item_purchase_option_license_fees) {
    primary_key(id) : INT
    plan_id : INT
    format_type_id: INT
    fee : DECIMAL
    license_id : INT
}

Table(stock_item_licenses) {
    primary_key(id) : INT
    title : INT
    description: TEXT
    public_url : DECIMAL
}

stock_item_purchase_option_license_fees --RIGHT-> stock_item_licenses : license_id::id
shopping_cart_stock_item_purchase_options --> stock_item_purchase_option_license_fees : licnese_fee_id::id
shopping_cart_purchase_stock_items ..UP.> stock_item_purchase_option_license_fees : snapshot of fee after purchase

@enduml