@startuml purchase_schema

!include lib/schema-style.iuml

:user identifies item to purchase;

if (enterprise user type) then (corp)
    partition "Enterprise Corp" {
    :user adds markeplace item to cart;
    :user checks out;
    }
else (api)
    partition "Enterprise API" {
    :user downloads
    marketplace item;
    }
endif

shopping_cart_purchases created;


@enduml
